spring:
  application:
    name: ledger-service

  datasource:
    url: jdbc:h2:mem:ledger_db
    driver-class-name: org.h2.Driver
    username: sa
    password: password

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        optimistic_locking: version
server:
  port: 8085

grpc:
  server:
    port: 9095

